databases:
  - name: ledger-postgres
    plan: free

services:
  - type: web
    name: ledger-finance-dashboard
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: DATABASE_URL
        fromDatabase:
          name: ledger-postgres
          property: connectionString
